export const CITIES = [
	"Mumbai",
	"Delhi",
	"Bangalore",
	"Kolkata",
	"Chennai",
	"Hyderabad",
	"Pune",
	"Ahmedabad",
	"Surat",
	"Jaipur",
	"Lucknow",
	"Nagpur",
	"Thane",
	"Bhopal",
	"Visakhapatnam",
	"Patna",
	"Vadodara",
	"Ludhiana",
	"Agra",
	"Nashik",
	"Faridabad",
	"Rajkot",
	"Varanasi",
	"Dhanbad",
	"Jodhpur",
	"Raipur",
	"Coimbatore",
	"Jabalpur",
	"Vijayawada",
	"Kanpur",
	"Indore",
	"Pimpri-Chinchwad",
	"Ghaziabad",
	"Meerut",
	"Kalyan-Dombivali",
	"Vasai-Virar",
	"Srinagar",
	"Amritsar",
	"Allahabad",
	"Gwalior",
];

export const STATE_CITIES =[
    { city: "Mumbai", state: "Maharashtra" },
    { city: "Delhi", state: "Delhi" },
    { city: "Bangalore", state: "Karnataka" },
    { city: "Kolkata", state: "West Bengal" },
    { city: "Chennai", state: "Tamil Nadu" },
    { city: "Hyderabad", state: "Telangana" },
    { city: "Pune", state: "Maharashtra" },
    { city: "Ahmedabad", state: "Gujarat" },
    { city: "Surat", state: "Gujarat" },
    { city: "Jaipur", state: "Rajasthan" },
    { city: "Lucknow", state: "Uttar Pradesh" },
    { city: "Nagpur", state: "Maharashtra" },
    { city: "Thane", state: "Maharashtra" },
    { city: "Bhopal", state: "Madhya Pradesh" },
    { city: "Visakhapatnam", state: "Andhra Pradesh" },
    { city: "Patna, Bihar", state: "Bihar" },
    { city: "Vadodara", state: "Gujarat" },
    { city: "Ludhiana", state: "Punjab" },
    { city: "Agra", state: "Uttar Pradesh" },
    { city: "Nashik", state: "Maharashtra" },
    { city: "Faridabad", state: "Haryana" },
    { city: "Rajkot", state: "Gujarat" },
    { city: "Varanasi", state: "Uttar Pradesh" },
    { city: "Dhanbad", state: "Jharkhand" },
    { city: "Jodhpur", state: "Rajasthan" },
    { city: "Raipur", state: "Chhattisgarh" },
    { city: "Coimbatore", state: "Tamil Nadu" },
    { city: "Jabalpur", state: "Madhya Pradesh" },
    { city: "Vijayawada", state: "Andhra Pradesh" },
    { city: "Kanpur", state: "Uttar Pradesh" },
    { city: "Indore", state: "Madhya Pradesh" },
    { city: "Pimpri-Chinchwad", state: "Maharashtra" },
    { city: "Ghaziabad", state: "Uttar Pradesh" },
    { city: "Meerut", state: "Uttar Pradesh" },
    { city: "Kalyan-Dombivali", state: "Maharashtra" },
    { city: "Vasai-Virar", state: "Maharashtra" },
    { city: "Srinagar", state: "Jammu and Kashmir" },
    { city: "Amritsar", state: "Punjab" },
    { city: "Allahabad", state: "Uttar Pradesh" },
    { city: "Gwalior", state: "Madhya Pradesh" },
  ]

export const BUS_OFFERS = [
    "https://static.abhibus.com/offerbanners/Jun2024/14/1718370073-720x360_blue.webp",
    "https://static.abhibus.com/offerbanners/Jun2024/04/1717451157-upsrtc-bus-offer.webp",
    "https://static.abhibus.com/offerbanners/Mar2024/01/1709246907-win-an-iphone-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/04/1717450409-hrtc-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Mar2024/01/1709246907-win-an-iphone-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/14/1718358379-720x360.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/04/1717449074-abhiparty-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/04/1717450757-rsrtc-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/06/1717662004-au-bank-bus-offer.webp",
     "https://static.abhibus.com/busgallery/offerbanners/Nov2023/07/1699342709-720x360-ixigo-au.png",
     "https://static.abhibus.com/offerbanners/Jun2024/04/1717449596-apsrtc-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/06/1717662342-icici-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/04/1717449925-tsrtc-bus-offer.webp",
     "https://static.abhibus.com/offerbanners/Jun2024/06/1717662820-mobikwik-bus-offer.webp",
     
]


export const HOTEL_LOCATIONS = [
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Bangalore, Karnataka",
  "Kolkata, West Bengal",
  "Chennai, Tamil Nadu",
  "Hyderabad, Telangana",
  "Pune, Maharashtra",
  "Ahmedabad, Gujarat",
  "Surat, Gujarat",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Rajkot, Gujarat",
  "Varanasi, Uttar Pradesh",
  "Dhanbad, Jharkhand",
  "Jodhpur, Rajasthan",
  "Raipur, Chhattisgarh",
  "Coimbatore, Tamil Nadu",
  "Jabalpur, Madhya Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Kanpur, Uttar Pradesh",
  "Indore, Madhya Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Ghaziabad, Uttar Pradesh",
  "Meerut, Uttar Pradesh",
  "Kalyan-Dombivali, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Srinagar, Jammu and Kashmir",
  "Amritsar, Punjab",
  "Allahabad, Uttar Pradesh",
  "Gwalior, Madhya Pradesh"
]

export const stationsArr= [
  {id:1, name:"Agra Cantonment"},
  {id:2, name:"Ahmedabad Junction"},
  {id:3, name:"Ambala Cantonment"},
  {id:4, name:"Amritsar Junction"},
  {id:5, name:"Anand Junction"},
  {id:6, name:"Barddhaman Junction"},
  {id:7, name:"Bengaluru City Junction"},
  {id:8, name:"Chandigarh"},
  {id:9, name:"Chennai Central"},
  {id:10, name:"Coimbatore Junction"},
  {id:11, name:"Delhi Junction"},
  {id:12, name:"Dhanbad Junction"},
  {id:13, name:"Gorakhpur Junction"},
  {id:14, name:"Guwahati"},
  {id:15, name:"Hazrat Nizamuddin"},
  {id:16, name:"Howrah Junction"},
  {id:17, name:"Hubli Junction"},
  {id:18, name:"Indore Junction"},
  {id:19, name:"Kalyan Junction"},
  {id:20, name:"Kanpur Central"},
  {id:21, name:"Katpadi Junction"},
  {id:22, name:"Kharagpur Junction"},
  {id:23, name:"Kollam Junction"},
  {id:24, name:"Lucknow Charbhagh"},
  {id:25, name:"Ludhiana Junction"},
  {id:26, name:"Manmad Junction"},
  {id:27, name:"Moradabad Junction"},
  {id:28, name:"Mughal Sarai Junction"},
  {id:29, name:"Mysuru Junction"},
  {id:30, name:"Nadiad Junction"},
  {id:31, name:"Nagpur Junction"},
  {id:32, name:"Patna Junction"},
  {id:33, name:"Pune Junction"},
  {id:34, name:"Raipur Junction"},
  {id:35, name:"Salem Junction"},
  {id:36, name:"Secunderabad Junction"},
  {id:37, name:"Surat"},
  {id:38, name:"Thiruvananthapuram Central"},
  {id:39, name:"Thrissur"},
  {id:40, name:"Udaipur City"},
  {id:41, name:"Vadodara Junction"},
  {id:42, name:"Varanasi Junction"},
  {id:43, name:"Vellore Katpadi"},
  {id:44, name:"Vijayawada Junction"},
  {id:45, name:"Visakhapatnam Junction"},
  {id:46, name:"Warangal"}
] 
